### ISSUE TITLE
'IPSelf' object has no attribute 'ton'

### ISSUE THREAD

**Issue by mrekai** [Exa-Networks/exabgp#316]
Injecting routes from a health check script had worked fine on 3.4.8, but now fail.  Announcements are of the form "announce route ${self_anycast_net} next-hop self" where ${self_anycast_net} is an IPv6 /128 address.  BGP is IPv6 only.

ExaBGP version : 3.9.0
Python version : 2.7.10 (default, Aug 12 2015, 08:03:41)  [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]
System Uname   : FreeBSD 10.1-RELEASE-p10 #0: Wed May 13 06:54:13 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC
System MaxInt  : 9223372036854775807

peer fec0:fdf8:1d0:a1::1 ASN 65003   

<type 'exceptions.AttributeError'>
'IPSelf' object has no attribute 'ton'
Traceback (most recent call last):
  File "/usr/local/exabgp-master/lib/exabgp/reactor/peer.py", line 613, in _run
    for action in self._main(direction):
  File "/usr/local/exabgp-master/lib/exabgp/reactor/peer.py", line 563, in _main
    new_routes.next()
  File "/usr/local/exabgp-master/lib/exabgp/reactor/protocol.py", line 305, in new_update
    for message in update.messages(self.negotiated):
  File "/usr/local/exabgp-master/lib/exabgp/bgp/message/update/__init__.py", line 200, in messages
    packed = mp_packed_generator.next()
  File "/usr/local/exabgp-master/lib/exabgp/bgp/message/update/attribute/mprnlri.py", line 70, in packed_attributes
    nexthop = nlri.nexthop.ton()
AttributeError: 'IPSelf' object has no attribute 'ton'

**Comment by thomas-mangin** [comment]
If you are not running the 3.4 stable branch or a release, could you please confirm that this bug is still present on the latest master .. I believe I had fixed it already part of the normal development process.

**Comment by mrekai** [comment]
It is not present in 3.4.8 (from FreeBSD ports).  It is present in 3.9.0 as of today when downloading master from GitHub.

For the time being, I'm fine remaining on 3.4.8, though a few quirks there (unrelated to this, possibly due to my lack of wisdom) led to trying some later versions.

**Comment by thomas-mangin** [comment]
Thank you - I will fix asap .. please let me enjoy my last two days of holidays ..

**Comment by mrekai** [comment]
No worries.  Enjoy and thanks.

**Comment by thomas-mangin** [comment]
Hello @mrekai can you please try again, I may have fixed the issue ( I am in a meeting so I did not test the fix yet .. )

**Comment by calhau69** [comment]
Hi,

Was I had reported in the chat I have found this problem again. My logs and config follows in attach.

Thank you.

[exabgp.log.txt](https://github.com/Exa-Networks/exabgp/files/33042/exabgp.log.txt)
[exabgp.conf.txt](https://github.com/Exa-Networks/exabgp/files/33041/exabgp.conf.txt)

**Comment by thomas-mangin** [comment]
Hopefully this helps ... crossing fingers. (not tested)

**Comment by calhau69** [comment]
Seems it didn't work... :S 
[exabgp.log.txt](https://github.com/Exa-Networks/exabgp/files/33447/exabgp.log.txt)

**Comment by thomas-mangin** [comment]
Hello @calhau69 - are you sure to be running the latest master as I could not reproduce the issue.
I have added a test for this too and it runs without issues:
https://github.com/Exa-Networks/exabgp/commit/c385b78b46fb6161f2fcc4971bcc3a08c32205fb

**Comment by calhau69** [comment]
I have the exabgp running on a VM that doesn't have GIT installed so download all the master from the GIT.  Here are some screenshots were you can see you code changes.

![screenshot from 2015-11-13 14 34 38](https://cloud.githubusercontent.com/assets/15329868/11148296/e7d982c8-8a13-11e5-89d9-555892dc808a.png)
![screenshot from 2015-11-13 14 33 44](https://cloud.githubusercontent.com/assets/15329868/11148295/e7d8aede-8a13-11e5-91f2-9077a9327fdb.png)

**Comment by thomas-mangin** [comment]
@calhau69 - the screenshots could be from the last version or not .. can you please run :
> ./qa/bin/conversation

and tell me if you see a test called ipself being been run ?

**Comment by calhau69** [comment]
Seems not...

![screenshot from 2015-11-13 17 11 36](https://cloud.githubusercontent.com/assets/15329868/11152299/a184125a-8a29-11e5-9587-86e9474c2555.png)
![screenshot from 2015-11-13 17 11 06](https://cloud.githubusercontent.com/assets/15329868/11152300/a1873a20-8a29-11e5-971e-5d92944c4be7.png)

**Comment by thomas-mangin** [comment]
I am a monkey - forgot to add a file so the test was not run anyway - if you have the files in the qa folder ./qa/conf/ipself.conf - then you have the latest version and I need more info

**Comment by calhau69** [comment]
Hi @thomas-mangin 

Finally I was able to test the new version of exabgp but I'm still getting the error on V6...
Here is the log.
[exabgplog.txt](https://github.com/Exa-Networks/exabgp/files/38855/exabgplog.txt)

And the screenshot here you see that I have the latest version running...
![screenshot from 2015-11-19 13 05 31](https://cloud.githubusercontent.com/assets/15329868/11269240/75c04c12-8ebe-11e5-9330-1ea02858385b.png)

Thank you!

**Comment by thomas-mangin** [comment]
Sorry I forgot to update the ticket - I wrote a patch which seems to work but it breaks the unit testing so I need to work on this side.
