### ISSUE TITLE
aggregator clause causes an exception on 3.4.6

### ISSUE THREAD

**Issue by tim-preston** [Exa-Networks/exabgp#212]
Attempting to set an ```aggregator``` clause on a prefix causes an error on 3.4.6

```
ExaBGP version : 3.4.6
Python version : 2.7.7 (default, Oct 28 2014, 13:30:28)  [GCC 4.8.3]
System Uname   : #1 SMP Wed Oct 8 12:26:01 BST 2014
System MaxInt  : 9223372036854775807


peer 195.66.225.230 ASN 8714    

<type 'exceptions.AttributeError'>
'bool' object has no attribute 'asn4'
Traceback (most recent call last):
  File "/home/tim/exabgp/exabgp-3.4.6/lib/exabgp/reactor/peer.py", line 589, in _run
    for action in self._main(direction):
  File "/home/tim/exabgp/exabgp-3.4.6/lib/exabgp/reactor/peer.py", line 539, in _main
    new_routes.next()
  File "/home/tim/exabgp/exabgp-3.4.6/lib/exabgp/reactor/protocol.py", line 270, in new_update
    for message in update.messages(self.negotiated):
  File "/home/tim/exabgp/exabgp-3.4.6/lib/exabgp/bgp/message/update/__init__.py", line 130, in messages
    attr = self.attributes.pack(negotiated,True)
  File "/home/tim/exabgp/exabgp-3.4.6/lib/exabgp/bgp/message/update/attribute/__init__.py", line 235, in pack
    message += self[code].pack(negotiated)
  File "/home/tim/exabgp/exabgp-3.4.6/lib/exabgp/bgp/message/update/attribute/aggregator.py", line 31, in pack
    return self._attribute(self.asn.pack(True)+self.speaker.pack())
  File "/home/tim/exabgp/exabgp-3.4.6/lib/exabgp/bgp/message/open/asn.py", line 19, in pack
    asn4 = negotiated.asn4 if negotiated else self.asn4()
AttributeError: 'bool' object has no attribute 'asn4'
```

Sample config to to trip this - this goes through the parser fine, but throws the above exception as soon as it tries to announce the prefix.
```
neighbor 195.66.225.230 {
  router-id 62.117.100.254;
  local-address 195.66.225.117;
  local-as 8732;
  peer-as 8714;
  group-updates;

  static {
    route 81.200.112.0/20 {
      next-hop 195.66.225.117;
      origin igp;
      as-path [ 8732 8595 33902 ];
      community [ 0:2578 0:9002 0:42861 8732:1000 ];
      aggregator ( 33902:79.141.224.1 );
    }
  }
}
```

Removing the ```aggregator``` clause clears the issue. This was working fine on 3.3.2, I haven't tested on versions between 3.3.2 and 3.4.6

**Comment by thomas-mangin** [comment]
Hello, this is already fixed in the latest master.

**Comment by thomas-mangin** [comment]
I will release 3.4.7 to fix the issue as it may be more important than I first thought

**Comment by thomas-mangin** [comment]
released, thank you for reporting the issue :+1:
